import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Deploys straight into the sibling vault's plugin folder so `npm run dev`
// (watch mode) makes edits live in a running Obsidian instance immediately.
// See CLAUDE.md / the AethersWeb plan for why the source tree lives outside the vault.
const outDir = path.resolve(__dirname, "../AethersWeb/.obsidian/plugins/aethersweb");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE. Source lives in aethersweb-plugin/src/.
Do not edit main.js directly — run \`npm run build\` or \`npm run dev\` instead.
*/
`;

const watch = process.argv[2] === "watch";

fs.mkdirSync(outDir, { recursive: true });

/** Copy manifest.json and styles.css into the deploy folder. */
function copyStaticFiles() {
	for (const name of ["manifest.json", "styles.css"]) {
		fs.copyFileSync(path.join(__dirname, name), path.join(outDir, name));
	}
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: [path.join(__dirname, "src/main.ts")],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: watch ? "inline" : false,
	treeShaking: true,
	outfile: path.join(outDir, "main.js"),
	minify: !watch,
});

copyStaticFiles();

if (watch) {
	await context.watch();
	console.log(`Watching, deploying to ${outDir}`);
} else {
	await context.rebuild();
	await context.dispose();
	console.log(`Built, deployed to ${outDir}`);
}
