import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// No shebang here — src/server.ts already starts with one, and esbuild keeps a leading shebang
// exactly at line 1 of the entry point's own source (banner text would otherwise land above it
// and break the "must be the very first bytes of the file" rule Node enforces for it).
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE. Source lives in mcp-server/src/ (and ../src/core/, shared with
the Obsidian plugin). Do not edit dist/server.js directly — run \`npm run build\` or \`npm run dev\`
instead.
*/
`;

const watch = process.argv[2] === "watch";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: [path.join(__dirname, "src/server.ts")],
	bundle: true,
	platform: "node",
	format: "esm",
	target: "node18",
	external: [...builtins],
	logLevel: "info",
	sourcemap: watch ? "inline" : false,
	treeShaking: true,
	outfile: path.join(__dirname, "dist/server.js"),
	minify: !watch,
});

if (watch) {
	await context.watch();
	console.log("Watching mcp-server/src for changes");
} else {
	await context.rebuild();
	await context.dispose();
	console.log("Built mcp-server/dist/server.js");
}
