import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// No shebang here — src/server.ts already starts with one, and esbuild keeps a leading shebang
// exactly at line 1 of the entry point's own source (banner text would otherwise land above it
// and break the "must be the very first bytes of the file" rule Node enforces for it).
//
// The createRequire shim below exists because HTTP mode pulls in express (via the SDK's
// server/express.js), and several of its CJS dependencies call require() on Node builtins
// (e.g. "tty") at runtime. esbuild's ESM output has no ambient `require` to satisfy those calls —
// without this, bundled CJS deps fail at startup with "Dynamic require of ... is not supported."
// This is esbuild's own documented fix for bundling CJS into a Node ESM target.
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE. Source lives in mcp-server/src/ (and ../src/core/, shared with
the Obsidian plugin). Do not edit dist/server.js directly — run \`npm run build\` or \`npm run dev\`
instead.
*/
import { createRequire as __aethersweb_createRequire } from "node:module";
const require = __aethersweb_createRequire(import.meta.url);
`;

const watch = process.argv[2] === "watch";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: [path.join(__dirname, "src/server.ts")],
	bundle: true,
	platform: "node",
	format: "esm",
	target: "node18",
	external: [...builtins],
	logLevel: "info",
	sourcemap: watch ? "inline" : false,
	treeShaking: true,
	outfile: path.join(__dirname, "dist/server.js"),
	minify: !watch,
});

if (watch) {
	await context.watch();
	console.log("Watching mcp-server/src for changes");
} else {
	await context.rebuild();
	await context.dispose();
	console.log("Built mcp-server/dist/server.js");
}
